id.o: id.c main.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
main.o: main.c main.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
