aio.o: aio.c udel_output.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h ../../adadio/udel_comm/udel_daq.h ../../adadio/udel_comm/udel_drv.h 
close.o: ../docsrc/close.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h 
gsc_util_close.o: ../utils/gsc_util_close.c ../utils/gsc_utils.h 
gsc_util_count.o: ../utils/gsc_util_count.c ../utils/gsc_utils.h 
gsc_util_id.o: ../utils/gsc_util_id.c ../utils/gsc_utils.h 
gsc_util_kbhit.o: ../utils/gsc_util_kbhit.c ../utils/gsc_utils.h 
gsc_util_label.o: ../utils/gsc_util_label.c ../utils/gsc_utils.h 
gsc_util_open.o: ../utils/gsc_util_open.c ../utils/gsc_utils.h 
gsc_util_reg.o: ../utils/gsc_util_reg.c ../driver/gsc_common.h ../utils/gsc_utils.h 
gsc_util_reg_plx9080.o: ../utils/gsc_util_reg_plx9080.c ../driver/gsc_pci9080.h ../driver/gsc_common.h ../utils/gsc_utils.h 
gsc_util_select.o: ../utils/gsc_util_select.c ../utils/gsc_utils.h 
ioctl.o: ../docsrc/ioctl.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h 
main.o: main.c main.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
open.o: ../docsrc/open.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h 
udel_daq.o: ../../adadio/udel_comm/udel_daq.c ../../adadio/udel_comm/udel_daq.h ../../adadio/udel_comm/udel_drv.h 
udel_output.o: udel_output.c udel_output.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h ../../adadio/udel_comm/udel_daq.h ../../adadio/udel_comm/udel_drv.h 
util_auto_calibrate.o: ../utils/util_auto_calibrate.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_buffer_clear.o: ../utils/util_buffer_clear.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_buffer_mode.o: ../utils/util_buffer_mode.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_buffer_over_data.o: ../utils/util_buffer_over_data.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_buffer_over_frame.o: ../utils/util_buffer_over_frame.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_buffer_size.o: ../utils/util_buffer_size.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_buffer_status.o: ../utils/util_buffer_status.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_burst_ready.o: ../utils/util_burst_ready.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_burst_trigger.o: ../utils/util_burst_trigger.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_burst_trig_src.o: ../utils/util_burst_trig_src.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_channel_sel.o: ../utils/util_channel_sel.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_clock_enable.o: ../utils/util_clock_enable.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_clock_osc_src.o: ../utils/util_clock_osc_src.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_clock_ready.o: ../utils/util_clock_ready.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_clock_src.o: ../utils/util_clock_src.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_clock_sw.o: ../utils/util_clock_sw.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_config.o: ../utils/util_config.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_data_format.o: ../utils/util_data_format.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_fref.o: ../utils/util_fref.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_fsamp.o: ../utils/util_fsamp.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_fsamp.o: ../utils/util_fsamp.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_ground_sense.o: ../utils/util_ground_sense.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_id.o: ../utils/util_id.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_initialize.o: ../utils/util_initialize.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_irq_enable.o: ../utils/util_irq_enable.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_irq_sel.o: ../utils/util_irq_sel.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_irq_state.o: ../utils/util_irq_state.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_load_ready.o: ../utils/util_load_ready.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_load_request.o: ../utils/util_load_request.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_nclk.o: ../utils/util_nclk.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_nrate.o: ../utils/util_nrate.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_output_mode.o: ../utils/util_output_mode.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_query.o: ../utils/util_query.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_reg.o: ../utils/util_reg.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_sample_mode.o: ../utils/util_sample_mode.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_tx_io_mode.o: ../utils/util_tx_io_mode.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_tx_io_over_data.o: ../utils/util_tx_io_over_data.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_tx_io_over_frame.o: ../utils/util_tx_io_over_frame.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_tx_io_timeout.o: ../utils/util_tx_io_timeout.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
util_xcvr_type.o: ../utils/util_xcvr_type.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
write.o: ../docsrc/write.c ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h 
