id.o: id.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h ../driver/gsc_pci9080.h 
main.o: main.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
