close.o: close.c 16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h 
ioctl.o: ioctl.c 16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h 
open.o: open.c 16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h 
write.o: write.c 16ao20_dsl.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h 
