ain_buf_clear.o: ain_buf_clear.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
ain_buf_size.o: ain_buf_size.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
ain_buf_sts.o: ain_buf_sts.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h ../docsrc/adadio_dsl.h ../driver/adadio.h 
ain_chan_last.o: ain_chan_last.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h ../docsrc/adadio_dsl.h ../driver/adadio.h 
ain_mode.o: ain_mode.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
ain_nrate.o: ain_nrate.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
ain_trigger.o: ain_trigger.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
aout_ch_x_write.o: aout_ch_x_write.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
aout_enable.o: aout_enable.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
aout_strobe_enable.o: aout_strobe_enable.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
aout_strobe.o: aout_strobe.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
auto_calibrate.o: auto_calibrate.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
data_format.o: data_format.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
dio_pin_read.o: dio_pin_read.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
dio_pin_write.o: dio_pin_write.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
dio_port_dir.o: dio_port_dir.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
dio_port_read.o: dio_port_read.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
dio_port_write.o: dio_port_write.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
initialize.o: initialize.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
irq_enable.o: irq_enable.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
irq_sel.o: irq_sel.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
irq_status.o: irq_status.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h ../docsrc/adadio_dsl.h ../driver/adadio.h 
loopback_channel.o: loopback_channel.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
main.o: main.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
query.o: query.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
reg_mod.o: reg_mod.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
reg_read.o: reg_read.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
reg_write.o: reg_write.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
rx_io_mode.o: rx_io_mode.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
rx_io_timeout.o: rx_io_timeout.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
service.o: service.c main.h ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../utils/adadio_utils.h ../driver/adadio.h ../utils/gsc_utils.h ../utils/gsc_utils.h 
