main.o: main.c main.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
tx.o: tx.c main.h ../driver/16ao20.h ../driver/gsc_common.h ../driver/gsc_pci9080.h ../docsrc/16ao20_dsl.h ../driver/16ao20.h ../utils/16ao20_utils.h ../driver/16ao20.h ../utils/gsc_utils.h 
