dio.o: dio.c ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h main.h ../utils/gsc_utils.h 
main.o: main.c ../driver/adadio.h ../driver/gsc_common.h ../driver/gsc_pci9080.h main.h ../utils/gsc_utils.h 
